/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankaccount;

/**
 *
 * @author alyazzie
 */
public class AccountCreatedGUI extends javax.swing.JFrame {

    /**
     * Creates new form AccountCreatedGUI
     */
    public AccountCreatedGUI(AccountHolder holder) {
        initComponents();                
        
        txtCustomerID.setText(String.valueOf(holder.getCustomerId()));
        
        txtAccountToString.setText(holder.toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblCustomerID = new javax.swing.JLabel();
        lblWarning = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        lblAccountInfoHeader = new javax.swing.JLabel();
        txtAccountToString = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblHeader.setText("Congratulations on your new account!");
        getContentPane().add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, -1, -1));

        lblCustomerID.setText("Your new Customer ID is:");
        getContentPane().add(lblCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 77, -1, -1));

        lblWarning.setText("Please keep this number safe!");
        getContentPane().add(lblWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        txtCustomerID.setEnabled(false);
        getContentPane().add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 72, 165, -1));

        lblAccountInfoHeader.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblAccountInfoHeader.setText("Account Information:");
        getContentPane().add(lblAccountInfoHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 154, -1, -1));

        txtAccountToString.setEnabled(false);
        getContentPane().add(txtAccountToString, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 177, 331, 114));

        btnClose.setText("Close");
        btnClose.setSelected(true);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        setSize(new java.awt.Dimension(400, 353));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblAccountInfoHeader;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JTextField txtAccountToString;
    private javax.swing.JTextField txtCustomerID;
    // End of variables declaration//GEN-END:variables
}
