/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankaccount;

/**
 *
 * @author alyazzie
 */
public class BankAccountInformationGUI extends javax.swing.JDialog {
    private AccountHolder accountHolder;
    private DBAccount dbAccount;
    
    /**
     * Creates new form BankAccountInformationGUI
     * @param accountHolder
     * @param dbAccount
     */
    public BankAccountInformationGUI(AccountHolder accountHolder, DBAccount dbAccount) {
        super((java.awt.Frame) null, true);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        initComponents();
        this.accountHolder = accountHolder;
        this.dbAccount = dbAccount;
        
        txtFirstName.setText(this.accountHolder.getFirstName());
        txtLastName.setText(this.accountHolder.getLastName());
        txtStreet.setText(this.accountHolder.getStreet());
        txtCity.setText(this.accountHolder.getCity());
        txtState.setText(this.accountHolder.getState());
        txtZip.setText(String.valueOf(this.accountHolder.getZip()));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabAccountInfo = new javax.swing.JTabbedPane();
        tabUserInfo = new javax.swing.JPanel();
        panelUserPhoto = new javax.swing.JPanel();
        lblUserPhoto = new javax.swing.JLabel();
        panelAddress = new javax.swing.JPanel();
        lblStreet = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        panelUserName = new javax.swing.JPanel();
        panelUserNameFirstName = new javax.swing.JLabel();
        panelUserNameLastName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        btnUpdateName = new javax.swing.JButton();
        btnUpdateAddress = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabAccountInfo.setToolTipText("");

        tabUserInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUserPhoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.jpeg"))); // NOI18N
        panelUserPhoto.add(lblUserPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 110));

        tabUserInfo.add(panelUserPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 110));

        lblStreet.setText("Street: ");

        lblCity.setText("City: ");

        lblState.setText("State: ");

        lblZipCode.setText("Zip:");

        javax.swing.GroupLayout panelAddressLayout = new javax.swing.GroupLayout(panelAddress);
        panelAddress.setLayout(panelAddressLayout);
        panelAddressLayout.setHorizontalGroup(
            panelAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddressLayout.createSequentialGroup()
                        .addGroup(panelAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStreet)
                            .addComponent(lblCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStreet)
                            .addComponent(txtCity)))
                    .addGroup(panelAddressLayout.createSequentialGroup()
                        .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 201, Short.MAX_VALUE))
                    .addGroup(panelAddressLayout.createSequentialGroup()
                        .addComponent(lblState)
                        .addGap(18, 18, 18)
                        .addComponent(txtState)))
                .addContainerGap())
        );
        panelAddressLayout.setVerticalGroup(
            panelAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        tabUserInfo.add(panelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 370, 120));

        panelUserNameFirstName.setText("First Name: ");

        panelUserNameLastName.setText("Last Name: ");

        javax.swing.GroupLayout panelUserNameLayout = new javax.swing.GroupLayout(panelUserName);
        panelUserName.setLayout(panelUserNameLayout);
        panelUserNameLayout.setHorizontalGroup(
            panelUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUserNameLayout.createSequentialGroup()
                        .addComponent(panelUserNameFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(panelUserNameLayout.createSequentialGroup()
                        .addComponent(panelUserNameLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName)))
                .addContainerGap())
        );
        panelUserNameLayout.setVerticalGroup(
            panelUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUserNameLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(panelUserNameFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelUserNameLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabUserInfo.add(panelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 260, -1));

        btnUpdateName.setText("Update Name");
        btnUpdateName.setSelected(true);
        btnUpdateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNameActionPerformed(evt);
            }
        });
        tabUserInfo.add(btnUpdateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        btnUpdateAddress.setText("Update Address");
        btnUpdateAddress.setSelected(true);
        btnUpdateAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAddressActionPerformed(evt);
            }
        });
        tabUserInfo.add(btnUpdateAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        tabAccountInfo.addTab("User Info", tabUserInfo);

        getContentPane().add(tabAccountInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 350));

        setSize(new java.awt.Dimension(413, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNameActionPerformed
     
        this.accountHolder.setFirstName(txtFirstName.getText());
        this.accountHolder.setLastName(txtLastName.getText());
        dbAccount.update(this.accountHolder.getCustomerId(), this.accountHolder);
        setVisible(false);
    }//GEN-LAST:event_btnUpdateNameActionPerformed

    private void btnUpdateAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAddressActionPerformed

        this.accountHolder.setStreet(txtStreet.getText());
        this.accountHolder.setCity(txtCity.getText());
        this.accountHolder.setState(txtState.getText());
        this.accountHolder.setZip(Integer.parseInt(txtZip.getText()));
        this.dbAccount.update(this.accountHolder.getCustomerId(), this.accountHolder);
        setVisible(false);
        
    }//GEN-LAST:event_btnUpdateAddressActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateAddress;
    private javax.swing.JButton btnUpdateName;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblUserPhoto;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JPanel panelAddress;
    private javax.swing.JPanel panelUserName;
    private javax.swing.JLabel panelUserNameFirstName;
    private javax.swing.JLabel panelUserNameLastName;
    private javax.swing.JPanel panelUserPhoto;
    private javax.swing.JTabbedPane tabAccountInfo;
    private javax.swing.JPanel tabUserInfo;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
