/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.bankaccount;

import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Jman
 */
public class CloseAll extends javax.swing.JDialog {
    
    private Map<Integer, ArrayList<BankAccount>> acctdef;
    private int holderID;
    private DBBankAcct bank; 
    private DBAccount conn;
    /**
     * Creates new form CloseAll
     * @param acctdef
     * @param bank
     * @param conn
     */
    public CloseAll(Map<Integer, ArrayList<BankAccount>> acctdef, DBBankAcct bank,DBAccount conn) {
        super((java.awt.Frame) null, true);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        this.acctdef = acctdef;
        this.bank = bank;
        this.conn = conn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtBox = new javax.swing.JTextField();
        btnCloseAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Please enter your account holder ID. This number will start with 500");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        txtBox.setText("Account Holder Number");

        btnCloseAll.setText("Close Account");
        btnCloseAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(btnCloseAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCloseAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCloseAll.getAccessibleContext().setAccessibleName("Close Account");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAllActionPerformed
        // TODO add your handling code here:
        
        this.holderID = Integer.parseInt(txtBox.getText());
        if(acctdef.containsKey(holderID))
        {   
            int size = acctdef.get(holderID).size(); 
            
            for(BankAccount acct: acctdef.get(holderID))
            {
                bank.delete(acct.getAccountNumber());
            }
            conn.delete(holderID);
            
            JOptionPane.showMessageDialog(null, String.format("Closed account holder ID %d "
                    + "and %d assicoated bank accounts.", holderID, size ));
            setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(null, "That ID doesn't match our records!");
    }//GEN-LAST:event_btnCloseAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseAll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtBox;
    // End of variables declaration//GEN-END:variables
}
