/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankaccount;
import java.util.*;
/**
 *
 * @author alyazzie
 */
public class CreateAccountHolderGUI extends javax.swing.JDialog{
    
    private AccountHolder newAcct; 
    private BankAccount acct;
    ArrayList<Object> objs;
    /**
     * Creates new form CreateAccountHolderGUI
     */
    public CreateAccountHolderGUI()
    {   
        super((java.awt.Frame) null, true);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        objs = new ArrayList<>();
        initComponents();
    }
    
    public ArrayList<Object> returnObjs()
    {
        return objs;
        
    }
    
    public void close()
    {
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtFirstName = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setText("Enter the following Information:");
        getContentPane().add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblFirstName.setText("First Name: ");
        getContentPane().add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblLastName.setText("Last Name:");
        getContentPane().add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblStreet.setText("Street Address:");
        getContentPane().add(lblStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblCity.setText("City:");
        getContentPane().add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblState.setText("State:");
        getContentPane().add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jButton1.setText("Ok");
        jButton1.setSelected(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 55, 150, -1));

        lblZipCode.setText("Zip: ");
        getContentPane().add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 218, -1, -1));
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 85, 150, -1));
        getContentPane().add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 115, 200, -1));
        getContentPane().add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 145, 150, -1));
        getContentPane().add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 175, 100, -1));
        getContentPane().add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 100, -1));

        setSize(new java.awt.Dimension(331, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Create new Account Holder
        newAcct = new AccountHolder(txtFirstName.getText(), txtLastName.getText(), txtStreet.getText(), txtCity.getText(), txtState.getText(), Integer.valueOf(txtZipCode.getText()));              
        objs.add(newAcct);
       
        new AccountCreatedGUI(newAcct).setVisible(true);
        
        //Open up next screen
        CreateAccountTypeGUI account = new CreateAccountTypeGUI(newAcct.getCustomerId());
        account.setVisible(true);
        
        acct = account.getAccount();
        objs.add(acct);
        
       setVisible(false);
                      
    }//GEN-LAST:event_jButton1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
