/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankaccount;

/**
 *
 * @author alyazzie
 */
public class InitialDepositGUI extends javax.swing.JDialog {
    
    int panelOption;
    double deposit; 
    int taxIncome;
    int grossIncome;
    String bDay;
    
    /**
     * @param n
     * Creates new form InitialDepositGUI
     */
    public InitialDepositGUI(int n) {
        super((java.awt.Frame) null, true);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        this.panelOption = n;
        initComponents();
          if(panelOption == 1)
          {
            panelPremiumChecking.setVisible(false);
            panelStandardSavings.setVisible(false);
            panelHighYieldSavings.setVisible(false);
            panelTraditionalIRA.setVisible(false);
            panelRothIRA.setVisible(false);
          }
          else if(panelOption == 2)
          {   
            panelBasicChecking.setVisible(false);
            panelStandardSavings.setVisible(false);
            panelHighYieldSavings.setVisible(false);
            panelTraditionalIRA.setVisible(false);
            panelRothIRA.setVisible(false);
          }
          else if(panelOption == 3)
          {   
            panelPremiumChecking.setVisible(false);
            panelBasicChecking.setVisible(false);
            panelHighYieldSavings.setVisible(false);
            panelTraditionalIRA.setVisible(false);
            panelRothIRA.setVisible(false);
          }
          else if(panelOption == 4)
          { 
            panelPremiumChecking.setVisible(false);
            panelBasicChecking.setVisible(false);
            panelStandardSavings.setVisible(false);
            panelTraditionalIRA.setVisible(false);
            panelRothIRA.setVisible(false);
          }
          else if(panelOption == 5)
          {
            panelPremiumChecking.setVisible(false);
            panelBasicChecking.setVisible(false);
            panelStandardSavings.setVisible(false);
            panelHighYieldSavings.setVisible(false);
            panelRothIRA.setVisible(false);
          }
          else
          {
            panelPremiumChecking.setVisible(false);
            panelBasicChecking.setVisible(false);
            panelStandardSavings.setVisible(false);
            panelHighYieldSavings.setVisible(false);
            panelTraditionalIRA.setVisible(false);
          }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblInitialDeposit = new javax.swing.JLabel();
        panelChecking = new javax.swing.JPanel();
        panelBasicChecking = new javax.swing.JPanel();
        lblBasicChecking = new javax.swing.JLabel();
        lblBasicChkDollarSign = new javax.swing.JLabel();
        txtBasicChecking = new javax.swing.JTextField();
        panelPremiumChecking = new javax.swing.JPanel();
        lblPremiumChecking = new javax.swing.JLabel();
        lblPremChkDollarSign = new javax.swing.JLabel();
        txtPremChecking = new javax.swing.JTextField();
        panelSavings = new javax.swing.JPanel();
        panelStandardSavings = new javax.swing.JPanel();
        lblStandardSavings = new javax.swing.JLabel();
        lblStndSavingsDollarSign = new javax.swing.JLabel();
        txtStndSavings = new javax.swing.JTextField();
        panelHighYieldSavings = new javax.swing.JPanel();
        lblHighYieldSavings = new javax.swing.JLabel();
        lblHighYieldDollarSign = new javax.swing.JLabel();
        txtHighYield = new javax.swing.JTextField();
        panelIRA = new javax.swing.JPanel();
        panelTraditionalIRA = new javax.swing.JPanel();
        lblTradBirthdate = new javax.swing.JLabel();
        lblTradTaxIncome = new javax.swing.JLabel();
        lblTradTaxIncDollarSign = new javax.swing.JLabel();
        txtTradTaxIncome = new javax.swing.JTextField();
        lblTradInitDeposit = new javax.swing.JLabel();
        lblTradInitDollarSign = new javax.swing.JLabel();
        txtTradInitDeposit = new javax.swing.JTextField();
        jDateTradBirthdateSelection = new javax.swing.JTextField();
        panelRothIRA = new javax.swing.JPanel();
        lblRothBirthdate = new javax.swing.JLabel();
        lblRothTaxIncome = new javax.swing.JLabel();
        lblRothTaxDollarSign = new javax.swing.JLabel();
        txtRothTaxIncome = new javax.swing.JTextField();
        lblRothGrossIncome = new javax.swing.JLabel();
        lblRothGrossDollarSign = new javax.swing.JLabel();
        txtRothGrossIncome = new javax.swing.JTextField();
        lblRothInitDeposit = new javax.swing.JLabel();
        lblRothInitDollarSign = new javax.swing.JLabel();
        txtRothInitDeposit = new javax.swing.JTextField();
        jDateRothBirthdateSelection = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblInitialDeposit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblInitialDeposit.setText("Enter any initial deposits:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(lblInitialDeposit, gridBagConstraints);

        panelChecking.setBorder(javax.swing.BorderFactory.createTitledBorder("Checking"));

        lblBasicChecking.setText("Basic Checking:");

        lblBasicChkDollarSign.setText("$");

        txtBasicChecking.setText("0.00");

        javax.swing.GroupLayout panelBasicCheckingLayout = new javax.swing.GroupLayout(panelBasicChecking);
        panelBasicChecking.setLayout(panelBasicCheckingLayout);
        panelBasicCheckingLayout.setHorizontalGroup(
            panelBasicCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBasicCheckingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBasicChecking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBasicChkDollarSign, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBasicChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelBasicCheckingLayout.setVerticalGroup(
            panelBasicCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBasicCheckingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBasicCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBasicChecking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBasicChkDollarSign, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBasicChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblPremiumChecking.setText("Premium Checking:");

        lblPremChkDollarSign.setText("$");

        txtPremChecking.setText("0.00");

        javax.swing.GroupLayout panelPremiumCheckingLayout = new javax.swing.GroupLayout(panelPremiumChecking);
        panelPremiumChecking.setLayout(panelPremiumCheckingLayout);
        panelPremiumCheckingLayout.setHorizontalGroup(
            panelPremiumCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPremiumCheckingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremiumChecking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPremChkDollarSign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPremChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPremiumCheckingLayout.setVerticalGroup(
            panelPremiumCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPremiumCheckingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPremiumCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPremiumChecking)
                    .addComponent(lblPremChkDollarSign)
                    .addComponent(txtPremChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCheckingLayout = new javax.swing.GroupLayout(panelChecking);
        panelChecking.setLayout(panelCheckingLayout);
        panelCheckingLayout.setHorizontalGroup(
            panelCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckingLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelBasicChecking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelCheckingLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panelPremiumChecking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCheckingLayout.setVerticalGroup(
            panelCheckingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckingLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(panelBasicChecking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(panelPremiumChecking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 10, 0, 26);
        getContentPane().add(panelChecking, gridBagConstraints);

        panelSavings.setBorder(javax.swing.BorderFactory.createTitledBorder("Savings"));

        lblStandardSavings.setText("Standard Savings:");

        lblStndSavingsDollarSign.setText("$");

        txtStndSavings.setText("0.00");

        javax.swing.GroupLayout panelStandardSavingsLayout = new javax.swing.GroupLayout(panelStandardSavings);
        panelStandardSavings.setLayout(panelStandardSavingsLayout);
        panelStandardSavingsLayout.setHorizontalGroup(
            panelStandardSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStandardSavingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStandardSavings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStndSavingsDollarSign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStndSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelStandardSavingsLayout.setVerticalGroup(
            panelStandardSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStandardSavingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStandardSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStandardSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStndSavingsDollarSign)
                    .addComponent(txtStndSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblHighYieldSavings.setText("High Yield Savings:");

        lblHighYieldDollarSign.setText("$");

        txtHighYield.setText("0.00");

        javax.swing.GroupLayout panelHighYieldSavingsLayout = new javax.swing.GroupLayout(panelHighYieldSavings);
        panelHighYieldSavings.setLayout(panelHighYieldSavingsLayout);
        panelHighYieldSavingsLayout.setHorizontalGroup(
            panelHighYieldSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHighYieldSavingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHighYieldSavings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHighYieldDollarSign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHighYield, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHighYieldSavingsLayout.setVerticalGroup(
            panelHighYieldSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHighYieldSavingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHighYieldSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHighYieldSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHighYieldDollarSign)
                    .addComponent(txtHighYield, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSavingsLayout = new javax.swing.GroupLayout(panelSavings);
        panelSavings.setLayout(panelSavingsLayout);
        panelSavingsLayout.setHorizontalGroup(
            panelSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSavingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelStandardSavings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelHighYieldSavings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSavingsLayout.setVerticalGroup(
            panelSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSavingsLayout.createSequentialGroup()
                .addComponent(panelStandardSavings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHighYieldSavings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 26);
        getContentPane().add(panelSavings, gridBagConstraints);

        panelIRA.setBorder(javax.swing.BorderFactory.createTitledBorder("IRA"));

        panelTraditionalIRA.setBorder(javax.swing.BorderFactory.createTitledBorder("Traditional IRA"));

        lblTradBirthdate.setText("Birthdate:");

        lblTradTaxIncome.setText("Taxable Income:");

        lblTradTaxIncDollarSign.setText("$");

        txtTradTaxIncome.setText("0.00");

        lblTradInitDeposit.setText("Initial Deposit:");

        lblTradInitDollarSign.setText("$");

        txtTradInitDeposit.setText("0.00");

        jDateTradBirthdateSelection.setText("yyyy-mm-dd");
        jDateTradBirthdateSelection.setActionCommand("<Not Set>");

        javax.swing.GroupLayout panelTraditionalIRALayout = new javax.swing.GroupLayout(panelTraditionalIRA);
        panelTraditionalIRA.setLayout(panelTraditionalIRALayout);
        panelTraditionalIRALayout.setHorizontalGroup(
            panelTraditionalIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTraditionalIRALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTraditionalIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTraditionalIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelTraditionalIRALayout.createSequentialGroup()
                            .addComponent(lblTradTaxIncome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTradTaxIncDollarSign))
                        .addGroup(panelTraditionalIRALayout.createSequentialGroup()
                            .addComponent(lblTradInitDeposit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTradInitDollarSign)))
                    .addComponent(lblTradBirthdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTraditionalIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTradTaxIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtTradInitDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jDateTradBirthdateSelection))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTraditionalIRALayout.setVerticalGroup(
            panelTraditionalIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTraditionalIRALayout.createSequentialGroup()
                .addGroup(panelTraditionalIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTraditionalIRALayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTradBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTraditionalIRALayout.createSequentialGroup()
                        .addComponent(jDateTradBirthdateSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTraditionalIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTradTaxIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTradTaxIncDollarSign)
                    .addComponent(txtTradTaxIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTraditionalIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTradInitDeposit)
                    .addComponent(lblTradInitDollarSign, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTradInitDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelRothIRA.setBorder(javax.swing.BorderFactory.createTitledBorder("Roth"));

        lblRothBirthdate.setText("BirthDate:");

        lblRothTaxIncome.setText("Taxable Income:");

        lblRothTaxDollarSign.setText("$");

        txtRothTaxIncome.setText("0.00");

        lblRothGrossIncome.setText("Gross Income:");

        lblRothGrossDollarSign.setText("$");

        txtRothGrossIncome.setText("0.00");

        lblRothInitDeposit.setText("Initial Deposit:");

        lblRothInitDollarSign.setText("$");

        txtRothInitDeposit.setText("0.00");

        jDateRothBirthdateSelection.setText("yyyy-mm-dd");

        javax.swing.GroupLayout panelRothIRALayout = new javax.swing.GroupLayout(panelRothIRA);
        panelRothIRA.setLayout(panelRothIRALayout);
        panelRothIRALayout.setHorizontalGroup(
            panelRothIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRothIRALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRothIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRothIRALayout.createSequentialGroup()
                        .addGroup(panelRothIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelRothIRALayout.createSequentialGroup()
                                .addComponent(lblRothGrossIncome)
                                .addGap(18, 18, 18)
                                .addComponent(lblRothGrossDollarSign))
                            .addGroup(panelRothIRALayout.createSequentialGroup()
                                .addComponent(lblRothInitDeposit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRothInitDollarSign)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRothIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRothGrossIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRothInitDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRothIRALayout.createSequentialGroup()
                        .addGroup(panelRothIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRothIRALayout.createSequentialGroup()
                                .addComponent(lblRothTaxIncome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRothTaxDollarSign))
                            .addComponent(lblRothBirthdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRothIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRothTaxIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jDateRothBirthdateSelection))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRothIRALayout.setVerticalGroup(
            panelRothIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRothIRALayout.createSequentialGroup()
                .addGroup(panelRothIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRothIRALayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRothBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateRothBirthdateSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRothIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRothTaxIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRothTaxDollarSign, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRothTaxIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRothIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRothGrossIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRothGrossDollarSign, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRothGrossIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRothIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRothInitDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRothInitDollarSign, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRothInitDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelIRALayout = new javax.swing.GroupLayout(panelIRA);
        panelIRA.setLayout(panelIRALayout);
        panelIRALayout.setHorizontalGroup(
            panelIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIRALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTraditionalIRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRothIRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        panelIRALayout.setVerticalGroup(
            panelIRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIRALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTraditionalIRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRothIRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 0, 26);
        getContentPane().add(panelIRA, gridBagConstraints);

        btnSubmit.setText("Submit");
        btnSubmit.setSelected(true);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 110, 9, 0);
        getContentPane().add(btnSubmit, gridBagConstraints);

        setSize(new java.awt.Dimension(326, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public double getInitDepo()
    {
        return this.deposit;
    }
    public int getGrossIn()
    {
        return this.grossIncome;
    }
    public int getTaxIn()
    {
        return this.taxIncome;
    }
    
    public String getBDay()
    {
        return this.bDay;
    }
    
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        switch(panelOption)
        {
            case 1:
                deposit = Double.parseDouble(txtBasicChecking.getText());
                break;
            case 2:
                deposit = Double.parseDouble(txtPremChecking.getText());
                break;
            case 3:
                deposit = Double.parseDouble(txtStndSavings.getText());
                break;
            case 4:
                deposit = Double.parseDouble(txtHighYield.getText());
                break;
            case 5:
                deposit = Double.parseDouble(txtTradInitDeposit.getText());
                taxIncome = Integer.parseInt(txtTradTaxIncome.getText());
                bDay = jDateTradBirthdateSelection.getText();
                break;
            case 6:
                deposit = Double.parseDouble(txtRothInitDeposit.getText());
                taxIncome = Integer.parseInt(txtTradTaxIncome.getText());
                bDay = jDateTradBirthdateSelection.getText();
                grossIncome = Integer.parseInt(txtRothGrossIncome.getText());
                break;
        }

        
        setVisible(false);
    }//GEN-LAST:event_btnSubmitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField jDateRothBirthdateSelection;
    private javax.swing.JTextField jDateTradBirthdateSelection;
    private javax.swing.JLabel lblBasicChecking;
    private javax.swing.JLabel lblBasicChkDollarSign;
    private javax.swing.JLabel lblHighYieldDollarSign;
    private javax.swing.JLabel lblHighYieldSavings;
    private javax.swing.JLabel lblInitialDeposit;
    private javax.swing.JLabel lblPremChkDollarSign;
    private javax.swing.JLabel lblPremiumChecking;
    private javax.swing.JLabel lblRothBirthdate;
    private javax.swing.JLabel lblRothGrossDollarSign;
    private javax.swing.JLabel lblRothGrossIncome;
    private javax.swing.JLabel lblRothInitDeposit;
    private javax.swing.JLabel lblRothInitDollarSign;
    private javax.swing.JLabel lblRothTaxDollarSign;
    private javax.swing.JLabel lblRothTaxIncome;
    private javax.swing.JLabel lblStandardSavings;
    private javax.swing.JLabel lblStndSavingsDollarSign;
    private javax.swing.JLabel lblTradBirthdate;
    private javax.swing.JLabel lblTradInitDeposit;
    private javax.swing.JLabel lblTradInitDollarSign;
    private javax.swing.JLabel lblTradTaxIncDollarSign;
    private javax.swing.JLabel lblTradTaxIncome;
    private javax.swing.JPanel panelBasicChecking;
    private javax.swing.JPanel panelChecking;
    private javax.swing.JPanel panelHighYieldSavings;
    private javax.swing.JPanel panelIRA;
    private javax.swing.JPanel panelPremiumChecking;
    private javax.swing.JPanel panelRothIRA;
    private javax.swing.JPanel panelSavings;
    private javax.swing.JPanel panelStandardSavings;
    private javax.swing.JPanel panelTraditionalIRA;
    private javax.swing.JTextField txtBasicChecking;
    private javax.swing.JTextField txtHighYield;
    private javax.swing.JTextField txtPremChecking;
    private javax.swing.JTextField txtRothGrossIncome;
    private javax.swing.JTextField txtRothInitDeposit;
    private javax.swing.JTextField txtRothTaxIncome;
    private javax.swing.JTextField txtStndSavings;
    private javax.swing.JTextField txtTradInitDeposit;
    private javax.swing.JTextField txtTradTaxIncome;
    // End of variables declaration//GEN-END:variables
}
