/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankaccount;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author alyazzie
 */
public class InitializeDepositWithdrawGUI extends javax.swing.JDialog {
    
    int panelOption;
    double amount;
//    CompleteDepositWithdrawGUI complete;
    private ArrayList<BankAccount> bankAccounts;
    private DBBankAcct bank;
    private  BankAccount account;
    
    /**
     * Creates new form InitializeDepositWithdraw
     * @param n
     * @param bankAccounts
     * @param bank
     */
    public InitializeDepositWithdrawGUI(int n, ArrayList<BankAccount> bankAccounts, DBBankAcct bank) {        
        super((java.awt.Frame) null, true);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        this.panelOption = n;
        initComponents();
        panelDeposit.setFocusable(true);
        panelWithdraw.setFocusable(true);
        this.bankAccounts = bankAccounts;
        this.bank = bank;
                
        if(panelOption == 1) //Deposit
        {                        
            lblDepositWithdrawHeader.setText("DEPOSIT");            
            panelWithdraw.setVisible(false);            
            btnSubmit.setText("Deposit");         
        }
        else if(panelOption == 2) //Withdraw
        {               
            lblDepositWithdrawHeader.setText("Withdraw");            
            panelDeposit.setVisible(false);
            btnSubmit.setText("Withdraw");
        }               
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDepositWithdrawHeader = new javax.swing.JLabel();
        panelDeposit = new javax.swing.JPanel();
        lblDeposit = new javax.swing.JLabel();
        txtDeposit = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        panelWithdraw = new javax.swing.JPanel();
        lblWithdraw = new javax.swing.JLabel();
        txtWithdraw = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAccountNumber = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDepositWithdrawHeader.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblDepositWithdrawHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDepositWithdrawHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblDepositWithdrawHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, 30));

        lblDeposit.setText("Enter the amount you would like to deposit:");

        txtDeposit.setText("0.00");
        txtDeposit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDepositFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepositFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelDepositLayout = new javax.swing.GroupLayout(panelDeposit);
        panelDeposit.setLayout(panelDepositLayout);
        panelDepositLayout.setHorizontalGroup(
            panelDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepositLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeposit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDepositLayout.setVerticalGroup(
            panelDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepositLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeposit)
                    .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        btnSubmit.setSelected(true);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        lblWithdraw.setText("Enter the Amount you would like to withdraw:");

        txtWithdraw.setText("0.00");
        txtWithdraw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWithdrawFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWithdrawFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelWithdrawLayout = new javax.swing.GroupLayout(panelWithdraw);
        panelWithdraw.setLayout(panelWithdrawLayout);
        panelWithdrawLayout.setHorizontalGroup(
            panelWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWithdrawLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWithdraw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelWithdrawLayout.setVerticalGroup(
            panelWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWithdrawLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWithdraw)
                    .addComponent(txtWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(panelWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel1.setText("Please enter the Account Number you would like to access:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(txtAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, -1));

        setSize(new java.awt.Dimension(453, 272));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        int accountNumber = Integer.parseInt(txtAccountNumber.getText());
        account = searchBankAccounts(bankAccounts, accountNumber);        
        
        if(account != null) 
        {
            if(getPanelOption() == 1) 
            {
                this.amount = Double.parseDouble(txtDeposit.getText());
                account.deposit(this.amount);
                bank.update(accountNumber, account.getBalance());
                
                
                setVisible(false);
                String html = "<html><body width='%1s'><h1>Success!</h1>"
                + "<p>You've deposited: $" + amount
                + "<br><br>"
                + "You're new balance is: $" + account.getBalance();
                // change to alter the width 
                int width = 250;
                JOptionPane.showMessageDialog(null, String.format(html, width, width));
            }
            else 
            {
                amount = Double.parseDouble(txtWithdraw.getText());
                if (account instanceof Traditional)
                {                    
                    ((Traditional) account).checkRequiredAge();
                    account.withdraw(amount); 
                    bank.update(accountNumber, account.getBalance());
                    
                }
                else 
                {                    
                    account.withdraw(amount);
                    bank.update(accountNumber, account.getBalance());
                    
                }
                setVisible(false);
                String html = "<html><body width='%1s'><h1>Success!</h1>"
                + "<p>Withdrawal Amount: $" + amount
                + "<br><br>"
                + "You're new balance is: $" + account.getBalance();
                // change to alter the width 
                int width = 250;
                JOptionPane.showMessageDialog(null, String.format(html, width, width));
            }           
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "Cannot find account with that account number! AcctNo: " + accountNumber);
        }
//        complete = new CompleteDepositWithdrawGUI(bankAccounts, accountNumber);
//        complete.setVisible(true);        
    }//GEN-LAST:event_btnSubmitActionPerformed

    public double getAmount()
    {
        return this.amount;
    }
    
    public double newBalance()
    {
        return account.getBalance();
    }
    
    private void txtDepositFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepositFocusGained
        if(txtDeposit.getText().equals("0.00")) {
            txtDeposit.setText("");
        }        
    }//GEN-LAST:event_txtDepositFocusGained

    private void txtWithdrawFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWithdrawFocusGained
       if(txtWithdraw.getText().equals("0.00")) {
            txtWithdraw.setText("");
        }      
    }//GEN-LAST:event_txtWithdrawFocusGained

    private void txtDepositFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepositFocusLost
        if(txtDeposit.getText().equals("")) {
            txtDeposit.setText("0.00");
        }  
    }//GEN-LAST:event_txtDepositFocusLost

    private void txtWithdrawFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWithdrawFocusLost
        if(txtWithdraw.getText().equals("")) {
            txtWithdraw.setText("0.00");
        }
    }//GEN-LAST:event_txtWithdrawFocusLost
    
    public int getPanelOption() {
        return this.panelOption;
    }
    
   // Search Bank Account method, returns the account
    public static BankAccount searchBankAccounts(ArrayList<BankAccount> bankAccounts, int accountNumber) {
        for (BankAccount bankAccount: bankAccounts) {
            if (bankAccount.getAccountNumber()== accountNumber) {
                return bankAccount;
            }
        }
        return null;
    } 
    
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InitializeDepositWithdrawGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InitializeDepositWithdrawGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InitializeDepositWithdrawGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InitializeDepositWithdrawGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InitializeDepositWithdrawGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDeposit;
    private javax.swing.JLabel lblDepositWithdrawHeader;
    private javax.swing.JLabel lblWithdraw;
    private javax.swing.JPanel panelDeposit;
    private javax.swing.JPanel panelWithdraw;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtDeposit;
    private javax.swing.JTextField txtWithdraw;
    // End of variables declaration//GEN-END:variables
}
