/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankaccount;

import java.util.ArrayList;
import java.util.Map;

/**
 *
 * @author alyazzie
 */
public class ViewAllAccountsGUI extends javax.swing.JDialog {

    /**
     * Creates new form ViewAllAccounts
     * @param holderID
     * @param acctdef
     * @param holder
     */
    public ViewAllAccountsGUI(int holderID,AccountHolder holder ,Map<Integer, ArrayList<BankAccount>> acctdef) 
    {   
        super((java.awt.Frame) null, true);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        initComponents();
        txtBox.append(holder.toString());
        txtBox.append("\n");
        
        int numOfAccounts = -1;
            if (acctdef.get(holder.getCustomerId()).isEmpty()) {
                numOfAccounts = 0;
                txtBox.append("\n");
                txtBox.append(String.format("%s %s, you have %d accounts with the Java Bank.\n", holder.getFirstName(), holder.getLastName(), numOfAccounts));
            }
            else
            {
                numOfAccounts = acctdef.get(holder.getCustomerId()).size();
                txtBox.append("\n");
                txtBox.append(String.format("%s %s, you have %d account(s) with the Java Bank. They are listed below:\n", holder.getFirstName(), holder.getLastName(), numOfAccounts));
                for (BankAccount account: acctdef.get(holder.getCustomerId())) {
                    
                    txtBox.append(account.toString());
                    txtBox.append("\n");
                }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBox = new java.awt.TextArea();

        btnClose.setText("Close");
        btnClose.setSelected(true);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your Account Info:");

        txtBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBox.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1)
                        .addGap(0, 245, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(txtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(648, 476));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextArea txtBox;
    // End of variables declaration//GEN-END:variables
}
